import { Address, Category, Order, Product } from "@src/Types/types";

export const mockCategories: Category[] = [
  {
    id: "c1",
    name: "Cement",
    description: "Bag cement and concrete compounds",
    icon_url: "https://images.unsplash.com/photo-1621905252472-e8f87d6b6f46?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c2",
    name: "Tiling",
    description: "Tile adhesives, grouts, and leveling tools",
    icon_url: "https://images.unsplash.com/photo-1618221118493-9cfa1a1c00da?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c3",
    name: "Painting",
    description: "Paints, primers, and finishing materials",
    icon_url: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c4",
    name: "Water Proofing",
    description: "Sealants and water-proofing compounds",
    icon_url: "https://images.unsplash.com/photo-1593941707882-a5bac6861d75?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c5",
    name: "Plywood, MDF & HDHMR",
    description: "Board sheets for carpentry and interiors",
    icon_url: "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c6",
    name: "Fevicol",
    description: "Adhesives for interior and carpentry applications",
    icon_url: "https://images.unsplash.com/photo-1594818379496-da1e345d9ca0?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c7",
    name: "General Hardware & Tools",
    description: "Nails, measuring tools, and misc. site hardware",
    icon_url: "https://images.unsplash.com/photo-1581147036324-c1c5f25f4d2f?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c8",
    name: "Kitchen & Home Appliances",
    description: "Essential appliances and utility kits",
    icon_url: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c9",
    name: "Hinges, Channels & Handles",
    description: "Drawer channels and cabinet fittings",
    icon_url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c10",
    name: "Kitchen Systems & Accessories",
    description: "Basket systems and modular accessories",
    icon_url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c11",
    name: "Wardrobe & Bed Fittings",
    description: "Hydraulic fittings and furniture supports",
    icon_url: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c12",
    name: "Door Locks & Hardware",
    description: "Locks, handles, and door accessories",
    icon_url: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c13",
    name: "Conduits & Pipes",
    description: "PVC conduits and heavy-duty plumbing pipes",
    icon_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c14",
    name: "Wires",
    description: "Copper and FRLS wire rolls",
    icon_url: "https://images.unsplash.com/photo-1518773553398-650c184e0bb3?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c15",
    name: "Switches & Sockets",
    description: "Modular switchgear and sockets",
    icon_url: "https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c16",
    name: "Lighting",
    description: "Bulbs, downlights, and fixtures",
    icon_url: "https://images.unsplash.com/photo-1493666438817-866a91353ca9?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c17",
    name: "Pipes",
    description: "CPVC, UPVC, PVC and Brass piping for all industrial needs.",
    icon_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c18",
    name: "Fittings",
    description: "Elbows, Ts, Caps and Unions in high-grade polymers.",
    icon_url: "https://images.unsplash.com/photo-1581428982868-e410dd1b11e9?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c19",
    name: "Taps",
    description: "Kitchen, bathroom, and utility taps with 5-year warranty.",
    icon_url: "https://plus.unsplash.com/premium_photo-1664300900010-062e74e6c986?w=300",
    created_at: new Date().toISOString(),
  },
  {
    id: "c20",
    name: "Valves",
    description: "Check valves, ball valves, and industrial gate controls.",
    icon_url: "https://images.unsplash.com/photo-1584622158864-4e2b02e77b4d?w=300",
    created_at: new Date().toISOString(),
  }
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "UltraTech OPC 53 Grade",
    description: "High-strength cement for slabs and structural pours.",
    price: 16,
    unit: "50 kg bag",
    category_id: "c1",
    image_url: "https://images.unsplash.com/photo-1621905252472-e8f87d6b6f46?w=500",
    stock: 500,
    created_at: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Roff Tile Adhesive T20",
    description: "Premium tile adhesive with quick-grip formulation.",
    price: 23,
    unit: "20 kg bag",
    category_id: "c2",
    image_url: "https://images.unsplash.com/photo-1618221118493-9cfa1a1c00da?w=500",
    stock: 320,
    created_at: new Date().toISOString(),
  },
  {
    id: "p3",
    name: "Interior Wall Primer",
    description: "Smooth coverage primer with strong adhesion.",
    price: 19,
    unit: "20 L bucket",
    category_id: "c3",
    image_url: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=500",
    stock: 800,
    created_at: new Date().toISOString(),
  },
  {
    id: "p4",
    name: "Flexi Waterproofing Coat",
    description: "Liquid membrane waterproofing for terraces and walls.",
    price: 28,
    unit: "10 kg pack",
    category_id: "c4",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bac6861d75?w=500",
    stock: 120,
    created_at: new Date().toISOString(),
  },
  {
    id: "p5",
    name: "HDHMR Board 18 mm",
    description: "High density board ideal for modular furniture.",
    price: 41,
    unit: "8 x 4 ft",
    category_id: "c5",
    image_url: "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=500",
    stock: 80,
    created_at: new Date().toISOString(),
  },
  {
    id: "p6",
    name: "Fevicol SH",
    description: "Synthetic resin adhesive for wood and laminates.",
    price: 11,
    unit: "1 kg jar",
    category_id: "c6",
    image_url: "https://images.unsplash.com/photo-1594818379496-da1e345d9ca0?w=500",
    stock: 90,
    created_at: new Date().toISOString(),
  },
  {
    id: "p7",
    name: "Laser Level Tool Kit",
    description: "Multi-point level and mounting toolkit for installation.",
    price: 34,
    unit: "1 set",
    category_id: "c7",
    image_url: "https://images.unsplash.com/photo-1581147036324-c1c5f25f4d2f?w=500",
    stock: 75,
    created_at: new Date().toISOString(),
  },
  {
    id: "p8",
    name: "Kitchen Chimney",
    description: "Compact chimney with dual-filter extraction.",
    price: 129,
    unit: "1 unit",
    category_id: "c8",
    image_url: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500",
    stock: 60,
    created_at: new Date().toISOString(),
  },
  {
    id: "p9",
    name: "CPVC Conduit Pipe",
    description: "Durable conduit for concealed electrical routes.",
    price: 7,
    unit: "3 m length",
    category_id: "c13",
    image_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500",
    stock: 210,
    created_at: new Date().toISOString(),
  },
  {
    id: "p10",
    name: "FR Wire Roll 1.5 sqmm",
    description: "Flame-retardant copper wire for home circuits.",
    price: 36,
    unit: "90 m roll",
    category_id: "c14",
    image_url: "https://images.unsplash.com/photo-1518773553398-650c184e0bb3?w=500",
    stock: 96,
    created_at: new Date().toISOString(),
  },
  {
    id: "p11",
    name: "Modular Switch Set",
    description: "Premium white switch and socket combo plate.",
    price: 22,
    unit: "1 kit",
    category_id: "c15",
    image_url: "https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=500",
    stock: 140,
    created_at: new Date().toISOString(),
  },
  {
    id: "p12",
    name: "LED Panel Light",
    description: "Energy-efficient LED panel for home interiors.",
    price: 18,
    unit: "1 unit",
    category_id: "c16",
    image_url: "https://images.unsplash.com/photo-1493666438817-866a91353ca9?w=500",
    stock: 145,
    created_at: new Date().toISOString(),
  },
  {
    id: "p13",
    name: "UPVC Schedule 40 Pipe",
    description: "Standard industrial grade UPVC Pipe.",
    price: 12,
    unit: "3 m length",
    category_id: "c17",
    image_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500",
    stock: 300,
    created_at: new Date().toISOString(),
  },
  {
    id: "p14",
    name: "CPVC Brass Elbow",
    description: "Durable elbow fitting for hot water.",
    price: 4,
    unit: "1 unit",
    category_id: "c18",
    image_url: "https://images.unsplash.com/photo-1581428982868-e410dd1b11e9?w=500",
    stock: 500,
    created_at: new Date().toISOString(),
  },
  {
    id: "p15",
    name: "Stainless Steel Basin Tap",
    description: "Rust-proof bathroom tap.",
    price: 35,
    unit: "1 unit",
    category_id: "c19",
    image_url: "https://plus.unsplash.com/premium_photo-1664300900010-062e74e6c986?w=500",
    stock: 120,
    created_at: new Date().toISOString(),
  },
  {
    id: "p16",
    name: "Heavy Duty Ball Valve",
    description: "Industrial ball valve for main lines.",
    price: 45,
    unit: "1 unit",
    category_id: "c20",
    image_url: "https://images.unsplash.com/photo-1584622158864-4e2b02e77b4d?w=500",
    stock: 80,
    created_at: new Date().toISOString(),
  }
];

export const mockOrders: Order[] = [
  {
    id: "27890765356",
    user_id: "mock-user",
    status: "delivered",
    total: 122,
    delivery_address: "Plot 14, Riverside Project Site",
    delivery_date: new Date().toISOString(),
    created_at: "2023-04-10T19:45:00.000Z",
  },
  {
    id: "89012399098",
    user_id: "mock-user",
    status: "out_for_delivery",
    total: 260,
    delivery_address: "Warehouse B, Industrial Zone",
    delivery_date: new Date().toISOString(),
    created_at: "2023-04-10T19:45:00.000Z",
  },
];

export const mockAddresses: Address[] = [
  {
    id: "a1",
    user_id: "mock-user",
    name: "Primary Yard",
    street: "4517 Washington Ave",
    city: "Manchester",
    state: "Kentucky",
    zip_code: "39495",
    phone: "(555) 010-1234",
    is_default: true,
  },
  {
    id: "a2",
    user_id: "mock-user",
    name: "Downtown Site",
    street: "2118 Thornridge Cir",
    city: "Syracuse",
    state: "Connecticut",
    zip_code: "35624",
    phone: "(555) 010-9876",
    is_default: false,
  },
];
